### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by bsde1245** [lordamit/jekyll-instant-article-facebook#1]
How to add username and password to feed?

**Comment by LordAmit** [comment]
Can you please elaborate? The feed is consumed by Facebook and should be publicly accessible.

**Comment by bsde1245** [comment]
[![Screenshot_20180228-115617.png](https://s14.postimg.org/5tfz1t7wh/Screenshot_20180228-115617.png)](https://postimg.org/image/90ailfscd/)

https://developers.facebook.com/docs/instant-articles/publishing/setup-rss-feed

**Comment by LordAmit** [comment]
Ah, as far as I understand, that should be something managed by the HTTP server and Jekyll, not this plugin.

**Comment by bsde1245** [comment]
Ok, Thanks. Closing...
